export const themeoneNewItem = {
  borderColor: '',
  bgColor: '',
  spotsSize: '',
  option: 'spot',
  spotOption: 1,
  spotText: '+',
  icon: '',
  image: '',
  tooltip: '<p>Tooltip contents</p>',
  tooltipPosition: 'left',
  position: {
    x: 0,
    y: 0,
  },
  iconColor: '',
  iconSize: '12px',
  spotLink:""
};
export const toolbarPositions = [
  { label: 'Default', value: 'left' },
  { label: 'Left', value: 'left' },
  { label: 'Top', value: 'top' },
  { label: 'Right', value: 'right' },
  { label: 'Bottom', value: 'bottom' },
  { label: 'Top Left', value: 'topleft' },
  { label: 'Top Right', value: 'topright' },
  { label: 'Bottom Left', value: 'bottomleft' },
  { label: 'Bottom Right', value: 'bottomright' },
];

export const defaultTheme = {
  bgColor: '#8a2be2',
  borderColor: '',
  height: { desktop: '40px', tablet: '40px', mobile: '40px' },
  heightDevice: 'desktop',
  width: { desktop: '40px', tablet: '40px', mobile: '40px' },
  widthDevice: 'desktop',
  padding: {
    desktop: {
      left: '0px',
      right: '0px',
      top: '0px',
      bottom: '0px',
    },
    tablet: {
      left: '0px',
      right: '0px',
      top: '0px',
      bottom: '0px',
    },
    mobile: {
      left: '0px',
      right: '0px',
      top: '0px',
      bottom: '0px',
    },
  },
  paddingDevice: 'desktop',
  borderRadius: {
    desktop: {
      left: '50px',
      right: '50px',
      top: '50px',
      bottom: '50px',
    },
    tablet: {
      left: '50px',
      right: '50px',
      top: '50px',
      bottom: '50px',
    },
    mobile: {
      left: '50px',
      right: '50px',
      top: '50px',
      bottom: '50px',
    },
  },
  borderRadiusDevice: 'desktop',
  borderWidth: {
    desktop: '0px',
    tablet: '0px',
    mobile: '0px',
  },
  borderWidthDevice: 'desktop',
  iconColor: '#fff',
  iconSize: { desktop: '12px', tablet: '12px', mobile: '12px' },
  iconSizeDevice: 'desktop',
  borderType: 'none',
  hover: 'normal',
  hoverColor: { icon: '#fff', bg: '', border: '' },
};

export const themeTwo = {
  bgColor: '#cd7418',
  borderColor: '',
  height: { desktop: '40px', tablet: '40px', mobile: '40px' },
  heightDevice: 'desktop',
  width: { desktop: '40px', tablet: '40px', mobile: '40px' },
  widthDevice: 'desktop',
  padding: {
    desktop: {
      left: '0px',
      right: '0px',
      top: '0px',
      bottom: '0px',
    },
    tablet: {
      left: '0px',
      right: '0px',
      top: '0px',
      bottom: '0px',
    },
    mobile: {
      left: '0px',
      right: '0px',
      top: '0px',
      bottom: '0px',
    },
  },
  paddingDevice: 'desktop',
  borderRadius: {
    desktop: {
      left: '50px',
      right: '50px',
      top: '50px',
      bottom: '5px',
    },
    tablet: {
      left: '50px',
      right: '50px',
      top: '50px',
      bottom: '5px',
    },
    mobile: {
      left: '50px',
      right: '50px',
      top: '50px',
      bottom: '5px',
    },
  },
  borderRadiusDevice: 'desktop',
  borderWidth: {
    desktop: '0px',
    tablet: '0px',
    mobile: '0px',
  },
  borderWidthDevice: 'desktop',
  iconColor: '#fff',
  iconSize: { desktop: '12px', tablet: '12px', mobile: '12px' },
  iconSizeDevice: 'desktop',
  borderType: 'none',
  hover: 'normal',
  hoverColor: { icon: '#fff', bg: '', border: '' },
};
export const themeThree = {
  bgColor: '#cd18bf',
  borderColor: '#fff',
  height: { desktop: '40px', tablet: '40px', mobile: '40px' },
  heightDevice: 'desktop',
  width: { desktop: '40px', tablet: '40px', mobile: '40px' },
  widthDevice: 'desktop',
  padding: {
    desktop: {
      left: '5px',
      right: '5px',
      top: '5px',
      bottom: '5px',
    },
    tablet: {
      left: '5px',
      right: '5px',
      top: '5px',
      bottom: '5px',
    },
    mobile: {
      left: '5px',
      right: '5px',
      top: '5px',
      bottom: '5px',
    },
  },
  paddingDevice: 'desktop',
  borderRadius: {
    desktop: {
      left: '50px',
      right: '50px',
      top: '50px',
      bottom: '50px',
    },
    tablet: {
      left: '50px',
      right: '50px',
      top: '50px',
      bottom: '50px',
    },
    mobile: {
      left: '50px',
      right: '50px',
      top: '50px',
      bottom: '50px',
    },
  },
  borderRadiusDevice: 'desktop',
  borderWidth: {
    desktop: '1px',
    tablet: '1px',
    mobile: '1px',
  },
  borderWidthDevice: 'desktop',
  iconColor: '#fff',
  iconSize: { desktop: '12px', tablet: '12px', mobile: '12px' },
  iconSizeDevice: 'desktop',
  borderType: 'solid',
  hover: 'normal',
  hoverColor: { icon: '#fff', bg: '', border: '' },
};
export const themeFour = {
  bgColor: '',
  borderColor: '#77cd18',
  height: { desktop: '40px', tablet: '40px', mobile: '40px' },
  heightDevice: 'desktop',
  width: { desktop: '40px', tablet: '40px', mobile: '40px' },
  widthDevice: 'desktop',
  padding: {
    desktop: {
      left: '5px',
      right: '5px',
      top: '5px',
      bottom: '5px',
    },
    tablet: {
      left: '5px',
      right: '5px',
      top: '5px',
      bottom: '5px',
    },
    mobile: {
      left: '5px',
      right: '5px',
      top: '5px',
      bottom: '5px',
    },
  },
  paddingDevice: 'desktop',
  borderRadius: {
    desktop: {
      left: '50px',
      right: '50px',
      top: '50px',
      bottom: '50px',
    },
    tablet: {
      left: '50px',
      right: '50px',
      top: '50px',
      bottom: '50px',
    },
    mobile: {
      left: '50px',
      right: '50px',
      top: '50px',
      bottom: '50px',
    },
  },
  borderRadiusDevice: 'desktop',
  borderWidth: {
    desktop: '2px',
    tablet: '2px',
    mobile: '2px',
  },
  borderWidthDevice: 'desktop',
  iconColor: '#77cd18',
  iconSize: { desktop: '16px', tablet: '16px', mobile: '16px' },
  iconSizeDevice: 'desktop',
  borderType: 'solid',
  hover: 'normal',
  hoverColor: { icon: '#77cd18', bg: '', border: '#77cd18' },
};

export const themeFive = {
  bgColor: '#3cbcd1a3',
  borderColor: '',
  height: { desktop: '40px', tablet: '40px', mobile: '40px' },
  heightDevice: 'desktop',
  width: { desktop: '100px', tablet: '100px', mobile: '100px' },
  widthDevice: 'desktop',
  padding: {
    desktop: {
      left: '5px',
      right: '5px',
      top: '5px',
      bottom: '5px',
    },
    tablet: {
      left: '5px',
      right: '5px',
      top: '5px',
      bottom: '5px',
    },
    mobile: {
      left: '5px',
      right: '5px',
      top: '5px',
      bottom: '5px',
    },
  },
  paddingDevice: 'desktop',
  borderRadius: {
    desktop: {
      left: '50px',
      right: '50px',
      top: '50px',
      bottom: '50px',
    },
    tablet: {
      left: '50px',
      right: '50px',
      top: '50px',
      bottom: '50px',
    },
    mobile: {
      left: '50px',
      right: '50px',
      top: '50px',
      bottom: '50px',
    },
  },
  borderRadiusDevice: 'desktop',
  borderWidth: {
    desktop: '2px',
    tablet: '2px',
    mobile: '2px',
  },
  borderWidthDevice: 'desktop',
  iconColor: '#fff',
  iconSize: { desktop: '25px', tablet: '25px', mobile: '25px' },
  iconSizeDevice: 'desktop',
  borderType: 'none',
  hover: 'normal',
  hoverColor: { icon: '#fff', bg: '', border: '' },
};
